name: Build and Deploy APK

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.4"

      - name: Get dependencies
        run: flutter pub get

      # Example 1: Basic build and deploy
      - name: Build and deploy APK
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          flavor: "shucked"
          groups: "testers"

      # Example 2: With release notes file
      - name: Build and deploy with release notes
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/shucked/main/main.dart"
          flavor: "shucked"
          release_notes_file: "deploy/release_notes.txt"
          groups: "testers,qa"

      # Example 3: With custom app ID
      - name: Build and deploy with custom app ID
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          firebase_app_id: "1:123456789:android:abcdef123456"
          groups: "testers"

      # Example 4: Build only (no deployment)
      - name: Build APK only
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          deploy: "false"

      # Example 5: Multiple flavors
      - name: Build and deploy production
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          flavor: "production"
          groups: "production-testers"
          release_notes_file: "deploy/release_notes.txt"

      - name: Build and deploy staging
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          flavor: "staging"
          groups: "staging-testers"
          release_notes_file: "deploy/release_notes.txt"

      # Example 6: Conditional deployment based on changed files
      - name: Build and deploy production (only if production files changed)
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          flavor: "production"
          groups: "production-testers"
          deploy_trigger_paths: |
            lib/flavors/production/
            android/app/src/production/
            pubspec.yaml

      - name: Build and deploy staging (only if staging files changed)
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/build-deploy-flutter-apk@main
        with:
          target_file: "lib/main.dart"
          flavor: "staging"
          groups: "staging-testers"
          deploy_trigger_paths: |
            lib/flavors/staging/
            android/app/src/staging/
            pubspec.yaml
