name: "Prepare Documentation"
description: "Prepare documentation by generating TOC and copying package files to docs directory"

inputs:
  dart_sdk:
    description: "Dart SDK version to use"
    required: false
    default: "3.5"
  project_root:
    description: "Root directory of the project (defaults to workspace)"
    required: false
    default: ${{ github.workspace }}
  docs_directory:
    description: "Directory where docs are located"
    required: false
    default: "docs"
  package_directories:
    description: 'Space-separated list of package directory patterns (e.g., "packages/*/ tools/*/")'
    required: false
    default: "packages/*/ tools/*/"
  toc_generator_path:
    description: "Path to the TOC generator script"
    required: false
    default: "scripts/toc_generator"
  generate_toc:
    description: "Whether to generate toc.json"
    required: false
    default: "true"
  copy_changelogs:
    description: "Whether to copy CHANGELOG.md files to docs directory"
    required: false
    default: "true"
  copy_readmes:
    description: "Whether to copy README.md files to docs directory"
    required: false
    default: "true"
  copy_docs_directories:
    description: "Whether to copy package docs/ directories to docs directory"
    required: false
    default: "true"
  copy_additional_md_files:
    description: "Whether to copy additional .md files from package root"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.dart_sdk }}

    - name: Generate toc.json
      if: inputs.generate_toc == 'true'
      shell: bash
      run: |
        cd ${{ inputs.toc_generator_path }}
        dart pub get --no-precompile
        dart bin/generate_toc.dart
        cd ${{ inputs.project_root }}
        cat ${{ inputs.docs_directory }}/toc.json

    - name: Copy CHANGELOGs to docs
      if: inputs.copy_changelogs == 'true'
      shell: bash
      run: |
        # Copy each package's CHANGELOG.md to docs/{package_name}/CHANGELOG.md
        for package_dir in ${{ inputs.package_directories }}; do
          package_name=$(basename "$package_dir")
          changelog_path="$package_dir/CHANGELOG.md"
          
          if [ -f "$changelog_path" ]; then
            mkdir -p "${{ inputs.docs_directory }}/$package_name"
            cp "$changelog_path" "${{ inputs.docs_directory }}/$package_name/CHANGELOG.md"
            echo "✅ Copied $package_name/CHANGELOG.md to ${{ inputs.docs_directory }}/$package_name/CHANGELOG.md"
          else
            echo "⚠️  No CHANGELOG.md found for $package_name"
          fi
        done

    - name: Copy READMEs to docs
      if: inputs.copy_readmes == 'true'
      shell: bash
      run: |
        # Copy each package's README.md to docs/{package_name}/README.md
        for package_dir in ${{ inputs.package_directories }}; do
          package_name=$(basename "$package_dir")
          readme_path="$package_dir/README.md"
          
          if [ -f "$readme_path" ]; then
            mkdir -p "${{ inputs.docs_directory }}/$package_name"
            cp "$readme_path" "${{ inputs.docs_directory }}/$package_name/README.md"
            echo "✅ Copied $package_name/README.md to ${{ inputs.docs_directory }}/$package_name/README.md"
          else
            echo "⚠️  No README.md found for $package_name"
          fi
        done

    - name: Copy package docs directories
      if: inputs.copy_docs_directories == 'true'
      shell: bash
      run: |
        # Copy all files from each package's docs/ directory to docs/{package_name}/
        for package_dir in ${{ inputs.package_directories }}; do
          package_name=$(basename "$package_dir")
          docs_dir="$package_dir/docs"
          
          if [ -d "$docs_dir" ]; then
            mkdir -p "${{ inputs.docs_directory }}/$package_name"
            # Copy all files from the package's docs directory, preserving structure
            find "$docs_dir" -type f -name "*.md" | while read -r doc_file; do
              # Get relative path from docs_dir
              rel_path="${doc_file#$docs_dir/}"
              target_dir="${{ inputs.docs_directory }}/$package_name/$(dirname "$rel_path")"
              mkdir -p "$target_dir"
              cp "$doc_file" "${{ inputs.docs_directory }}/$package_name/$rel_path"
              echo "✅ Copied $package_name/docs/$rel_path to ${{ inputs.docs_directory }}/$package_name/$rel_path"
            done
          else
            echo "ℹ️  No docs/ directory found for $package_name"
          fi
        done

    - name: Copy additional documentation files from package root
      if: inputs.copy_additional_md_files == 'true'
      shell: bash
      run: |
        # Copy any additional .md files from package root (excluding README.md and CHANGELOG.md)
        for package_dir in ${{ inputs.package_directories }}; do
          package_name=$(basename "$package_dir")
          
          # Find all .md files in package root that aren't README.md or CHANGELOG.md
          find "$package_dir" -maxdepth 1 -type f -name "*.md" ! -name "README.md" ! -name "CHANGELOG.md" | while read -r doc_file; do
            filename=$(basename "$doc_file")
            mkdir -p "${{ inputs.docs_directory }}/$package_name"
            cp "$doc_file" "${{ inputs.docs_directory }}/$package_name/$filename"
            echo "✅ Copied $package_name/$filename to ${{ inputs.docs_directory }}/$package_name/$filename"
          done
        done
