name: "Build and Deploy Flutter APK"
description: "Build Flutter APK and deploy to Firebase App Distribution"

inputs:
  # Build inputs
  target_file:
    description: "Target Dart file to build (e.g., lib/main.dart)"
    required: true
  flavor:
    description: "Build flavor (e.g., shucked, production)"
    required: false
    default: ""
  build_mode:
    description: "Build mode (release, debug, profile)"
    required: false
    default: "release"
  build_args:
    description: "Additional arguments for flutter build apk (e.g., --no-tree-shake-icons)"
    required: false
    default: ""
  apk_output_path:
    description: "Path to the built APK file (relative to workspace root)"
    required: false
    default: "build/app/outputs/apk/release/app-release.apk"

  # Gradle caching
  cache_gradle:
    description: "Whether to cache Gradle dependencies"
    required: false
    default: "true"

  # Firebase App ID
  firebase_app_id:
    description: "Firebase Android App ID. If not provided, will be extracted from firebase.json"
    required: false
    default: ""
  firebase_json_path:
    description: "Path to firebase.json file"
    required: false
    default: "firebase.json"
  app_id_path:
    description: "Path in firebase.json to extract app ID (e.g., 'flutter.platforms.android.default.appId')"
    required: false
    default: "flutter.platforms.android.default.appId"

  # Deployment inputs
  deploy:
    description: "Whether to deploy to Firebase App Distribution"
    required: false
    default: "true"
  deploy_trigger_paths:
    description: "Newline-separated list of paths/patterns that should trigger deployment. If provided, deployment only occurs if files matching these paths have changed. If empty, deployment happens based on 'deploy' input only."
    required: false
    default: ""
  firebase_project_id:
    description: "Firebase project ID"
    required: false
    default: ""
  release_notes_file:
    description: "Path to release notes file"
    required: false
    default: "deploy/release_notes.txt"
  release_notes:
    description: "Release notes text (alternative to release_notes_file)"
    required: false
    default: ""
  groups:
    description: "Comma-separated list of tester groups (e.g., 'testers,qa')"
    required: false
    default: "testers"
  testers:
    description: "Comma-separated list of tester emails"
    required: false
    default: ""
  service_account_path:
    description: "Path to Firebase service account JSON file"
    required: false
    default: "firebase_service_account.json"

runs:
  using: "composite"
  steps:
    - name: Check for skip deployment labels
      shell: bash
      id: check-skip-labels
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_LABELS_JSON: ${{ toJSON(github.event.pull_request.labels) }}
      run: |
        set -e

        FLAVOR="${{ inputs.flavor }}"
        EVENT_NAME="${{ github.event_name }}"
        SKIP_DEPLOY=false
        SKIP_REASON=""

        echo "🔍 Checking for skip deployment labels..."
        echo "📋 Event: $EVENT_NAME"
        echo "📋 Flavor: ${FLAVOR:-'(none)'}"
        echo ""

        # Function to normalize label name (lowercase, handle variations)
        normalize_label() {
          echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9:]//g'
        }

        # Function to check if a label should skip deployment
        should_skip() {
          local label="$1"
          local normalized_label=$(normalize_label "$label")
          
          # Check for generic "no-deploy" label (case-insensitive)
          if [ "$normalized_label" = "nodeploy" ] || [ "$normalized_label" = "no-deploy" ]; then
            return 0
          fi
          
          # Check for generic "no-deploy-apk" label (case-insensitive)
          if [ "$normalized_label" = "nodeployapk" ] || [ "$normalized_label" = "no-deploy-apk" ]; then
            return 0
          fi
          
          # Check for flavor-specific label (e.g., "no-deploy:shucked", "no deploy: shucked")
          if [ -n "$FLAVOR" ]; then
            local normalized_flavor=$(normalize_label "$FLAVOR")
            if echo "$normalized_label" | grep -qE "^nodeploy:${normalized_flavor}$|^no-deploy:${normalized_flavor}$"; then
              return 0
            fi
          fi
          
          # Check for APK flavor-specific label (e.g., "no-deploy-apk:shucked", "no deploy-apk: shucked")
          if [ -n "$FLAVOR" ]; then
            local normalized_flavor=$(normalize_label "$FLAVOR")
            if echo "$normalized_label" | grep -qE "^nodeployapk:${normalized_flavor}$|^no-deploy-apk:${normalized_flavor}$"; then
              return 0
            fi
          fi
          
          return 1
        }

        # Get labels based on event type
        if [ "$EVENT_NAME" = "pull_request" ]; then
          # For PR events, check labels directly from event
          echo "📋 Checking PR labels..."
          
          # Extract label names from JSON (set as environment variable)
          if [ -n "$PR_LABELS_JSON" ] && [ "$PR_LABELS_JSON" != "null" ] && [ "$PR_LABELS_JSON" != "[]" ]; then
            # Try using jq if available
            if command -v jq >/dev/null 2>&1; then
              PR_LABELS=$(echo "$PR_LABELS_JSON" | jq -r '.[].name' 2>/dev/null | tr '\n' ' ' || echo "")
            else
              # Fallback: extract using sed/grep
              PR_LABELS=$(echo "$PR_LABELS_JSON" | grep -oE '"name"\s*:\s*"[^"]+"' | sed 's/"name"\s*:\s*"//g' | sed 's/"//g' | tr '\n' ' ' || echo "")
            fi
            
            # Trim whitespace
            PR_LABELS=$(echo "$PR_LABELS" | xargs)
            
            if [ -z "$PR_LABELS" ]; then
              echo "ℹ️  No labels found on PR"
            else
              echo "📋 Found labels: $PR_LABELS"
              for label in $PR_LABELS; do
                if should_skip "$label"; then
                  SKIP_DEPLOY=true
                  SKIP_REASON="PR has skip label: $label"
                  echo "⏭️  Found skip label: $label"
                  break
                fi
              done
            fi
          else
            echo "ℹ️  No labels found on PR"
          fi
        else
          # For push events (e.g., after PR merge), try to get PR labels from commit message
          echo "📋 Checking merged PR labels from commit message..."
          
          # Extract PR number from commit message (GitHub merge commits typically include "Merge pull request #123")
          PR_NUMBER=$(git log -1 --pretty=%B | grep -oE 'Merge pull request #([0-9]+)|#([0-9]+)' | grep -oE '[0-9]+' | head -n 1 || echo "")
          
          if [ -n "$PR_NUMBER" ]; then
            echo "📋 Found PR number in commit: #$PR_NUMBER"
            
            # Use GitHub API to get PR labels
            API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
            echo "🔍 Fetching PR info from: $API_URL"
            
            # Fetch PR data (labels are in the response)
            PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" "$API_URL" || echo "")
            
            if [ -n "$PR_DATA" ] && echo "$PR_DATA" | grep -q '"labels"'; then
              # Extract label names from JSON response
              # Try using jq if available, otherwise use sed/awk
              if command -v jq >/dev/null 2>&1; then
                LABELS=$(echo "$PR_DATA" | jq -r '.labels[].name' 2>/dev/null | tr '\n' ' ' || echo "")
              else
                # Fallback: extract labels using sed (handles JSON arrays)
                LABELS=$(echo "$PR_DATA" | sed -n '/"labels":\s*\[/,/\]/p' | grep -oE '"name"\s*:\s*"[^"]+"' | sed 's/"name"\s*:\s*"//g' | sed 's/"//g' | tr '\n' ' ' || echo "")
              fi
              
              # Trim whitespace
              LABELS=$(echo "$LABELS" | xargs)
              
              if [ -n "$LABELS" ]; then
                echo "📋 Found labels on merged PR: $LABELS"
                for label in $LABELS; do
                  if should_skip "$label"; then
                    SKIP_DEPLOY=true
                    SKIP_REASON="Merged PR #$PR_NUMBER has skip label: $label"
                    echo "⏭️  Found skip label: $label"
                    break
                  fi
                done
              else
                echo "ℹ️  No labels found on merged PR"
              fi
            else
              echo "⚠️  Could not fetch PR data or PR not found (might be a direct push)"
            fi
          else
            echo "ℹ️  No PR number found in commit message (might be a direct push)"
          fi
        fi

        if [ "$SKIP_DEPLOY" = "true" ]; then
          echo ""
          echo "⏭️  Build and deployment will be skipped: $SKIP_REASON"
          echo "skip_deploy=true" >> $GITHUB_OUTPUT
        else
          echo ""
          echo "✅ No skip labels found, build and deployment will proceed"
          echo "skip_deploy=false" >> $GITHUB_OUTPUT
        fi

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      if: |
        inputs.cache_gradle == 'true' && 
        steps.check-skip-labels.outputs.skip_deploy != 'true'
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/*.gradle*', 'android/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Flutter APK
      shell: bash
      if: steps.check-skip-labels.outputs.skip_deploy != 'true'
      run: |
        TARGET_FILE="${{ inputs.target_file }}"
        FLAVOR="${{ inputs.flavor }}"
        BUILD_MODE="${{ inputs.build_mode }}"
        BUILD_ARGS="${{ inputs.build_args }}"

        echo "🔍 Building Flutter APK..."
        echo "📋 Target: $TARGET_FILE"
        echo "📋 Mode: $BUILD_MODE"
        echo "📋 APK output path: ${{ inputs.apk_output_path }}"

        # Build command
        BUILD_CMD="flutter build apk --$BUILD_MODE"

        # Add flavor if provided
        if [ -n "$FLAVOR" ]; then
          BUILD_CMD="$BUILD_CMD --flavor $FLAVOR"
          echo "📋 Flavor: $FLAVOR"
        fi

        # Add target file
        BUILD_CMD="$BUILD_CMD -t $TARGET_FILE"

        # Add additional arguments
        if [ -n "$BUILD_ARGS" ]; then
          BUILD_CMD="$BUILD_CMD $BUILD_ARGS"
        fi

        echo "🚀 Running: $BUILD_CMD"
        $BUILD_CMD

        echo "✅ APK build completed"

        echo "\n================================================"
        echo "Showing apk files in build directory..."
        find build -iname '*.apk' 
        echo "================================================\n"

        # Determine APK path if not explicitly set
        if [ "${{ inputs.apk_output_path }}" = "build/app/outputs/apk/release/app-release.apk" ]; then
          # Auto-detect APK path based on flavor
          if [ -n "$FLAVOR" ]; then
            # Try flavor-specific path
            FLAVOR_APK_PATH="build/app/outputs/apk/$FLAVOR/release/app-$FLAVOR-release.apk"
            if [ -f "$FLAVOR_APK_PATH" ]; then
              echo "APK_OUTPUT_PATH=$FLAVOR_APK_PATH" >> $GITHUB_ENV
              echo "📦 Detected APK at: $FLAVOR_APK_PATH"
            fi
          fi
        fi

        # Always set APK_OUTPUT_PATH to input value if not already set by auto-detection
        if [ -z "$APK_OUTPUT_PATH" ]; then
          echo "APK_OUTPUT_PATH=${{ inputs.apk_output_path }}" >> $GITHUB_ENV
          echo "📦 Using APK path: ${{ inputs.apk_output_path }}"
        fi

    - name: Show APK info and size
      shell: bash
      if: steps.check-skip-labels.outputs.skip_deploy != 'true'
      run: |
        echo "\n================================================"
        echo "🔍 Showing APK info and size..."
        echo "APK_OUTPUT_PATH: $APK_OUTPUT_PATH"
        echo "📋 APK info:"
        file "$APK_OUTPUT_PATH"
        echo "📋 APK size:"
        du -h "$APK_OUTPUT_PATH"
        echo "📋 APK details:"
        ls -l "$APK_OUTPUT_PATH"
        echo "================================================\n"

    - name: Artifact for APK
      uses: actions/upload-artifact@v4
      if: steps.check-skip-labels.outputs.skip_deploy != 'true'
      with:
        name: apk
        path: $APK_OUTPUT_PATH

    - name: Check if deployment should be triggered
      shell: bash
      id: check-deploy
      if: |
        inputs.deploy == 'true' && 
        inputs.deploy_trigger_paths != '' && 
        steps.check-skip-labels.outputs.skip_deploy != 'true'
      run: |
        set -e

        DEPLOY_TRIGGER_PATHS="${{ inputs.deploy_trigger_paths }}"

        echo "🔍 Checking if files in trigger paths have changed..."
        echo "📋 Watching paths:"
        echo "$DEPLOY_TRIGGER_PATHS" | sed 's/^/  - /'
        echo ""

        # Determine the base commit to compare against
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          BASE_REF="${{ github.event.pull_request.base.sha }}"
          echo "📋 Comparing PR branch against base: $BASE_BRANCH"
          git fetch origin "$BASE_BRANCH:$BASE_BRANCH" 2>/dev/null || echo "Could not fetch base branch"
        else
          # For pushes, compare against the previous commit
          BASE_REF="HEAD~1"
          echo "📋 Comparing against previous commit (HEAD~1)"
        fi

        # Check for changes in each trigger path
        HAS_CHANGES=false
        CHANGED_FILES=""

        # Process each path (split by newline)
        while IFS= read -r path; do
          # Skip empty lines
          [ -z "$path" ] && continue
          
          # Trim whitespace
          path=$(echo "$path" | xargs)
          
          # Check if path exists (as file or directory)
          if [ ! -e "$path" ] && [ ! -d "$path" ]; then
            echo "⚠️  Path does not exist: $path (will still check git diff)"
          fi
          
          # Check for changes using git diff (with fallbacks)
          CHANGED=""
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # Try multiple fallback strategies for PRs
            CHANGED=$(git diff --name-only "$BASE_REF" HEAD -- "$path" 2>/dev/null || \
                     git diff --name-only "$BASE_BRANCH" HEAD -- "$path" 2>/dev/null || \
                     git diff --name-only HEAD~1 HEAD -- "$path" 2>/dev/null || \
                     echo "")
          else
            # For pushes, compare against previous commit
            CHANGED=$(git diff --name-only "$BASE_REF" HEAD -- "$path" 2>/dev/null || echo "")
          fi
          
          if [ -n "$CHANGED" ]; then
            echo "✅ Found changes in: $path"
            echo "$CHANGED" | sed 's/^/    - /'
            HAS_CHANGES=true
            if [ -n "$CHANGED_FILES" ]; then
              CHANGED_FILES="$CHANGED_FILES"$'\n'"$CHANGED"
            else
              CHANGED_FILES="$CHANGED"
            fi
          else
            echo "⏭️  No changes in: $path"
          fi
        done <<< "$DEPLOY_TRIGGER_PATHS"

        if [ "$HAS_CHANGES" = "true" ]; then
          echo ""
          echo "✅ Deployment will be triggered (files changed in watched paths)"
          echo "should_deploy=true" >> $GITHUB_OUTPUT
        else
          echo ""
          echo "⏭️  Deployment will be skipped (no changes in watched paths)"
          echo "should_deploy=false" >> $GITHUB_OUTPUT
        fi

    - name: Extract Firebase Android App ID
      shell: bash
      id: firebase-app-id
      if: |
        inputs.deploy == 'true' && 
        steps.check-skip-labels.outputs.skip_deploy != 'true' &&
        inputs.firebase_app_id == '' && 
        (inputs.deploy_trigger_paths == '' || steps.check-deploy.outputs.should_deploy == 'true')
      run: |
        set -e
        FIREBASE_JSON="${{ inputs.firebase_json_path }}"
        APP_ID_PATH="${{ inputs.app_id_path }}"

        echo "🔍 Extracting Firebase Android App ID from $FIREBASE_JSON..."

        if [ ! -f "$FIREBASE_JSON" ]; then
          echo "❌ Firebase JSON file not found: $FIREBASE_JSON"
          exit 1
        fi

        SCRIPT_PATH="${{ github.action_path }}/extract_app_id.py"
        if [ ! -f "$SCRIPT_PATH" ]; then
          echo "❌ Helper script not found: $SCRIPT_PATH"
          exit 1
        fi

        APP_ID=$(python3 "$SCRIPT_PATH" "$FIREBASE_JSON" "$APP_ID_PATH")

        if [ -z "$APP_ID" ]; then
          echo "❌ Could not extract Android app ID from $FIREBASE_JSON"
          echo "📋 Tried path: $APP_ID_PATH"
          exit 1
        fi

        echo "✅ Extracted Android app ID: $APP_ID"
        echo "FIREBASE_APP_ID_ANDROID=$APP_ID" >> $GITHUB_ENV
        echo "app_id=$APP_ID" >> $GITHUB_OUTPUT

    - name: Set Firebase App ID
      shell: bash
      if: |
        inputs.deploy == 'true' && 
        steps.check-skip-labels.outputs.skip_deploy != 'true' &&
        inputs.firebase_app_id != '' && 
        (inputs.deploy_trigger_paths == '' || steps.check-deploy.outputs.should_deploy == 'true')
      run: |
        echo "✅ Using provided Firebase Android App ID: ${{ inputs.firebase_app_id }}"
        echo "FIREBASE_APP_ID_ANDROID=${{ inputs.firebase_app_id }}" >> $GITHUB_ENV

    - name: Deploy to Firebase App Distribution
      shell: bash
      if: |
        inputs.deploy == 'true' && 
        steps.check-skip-labels.outputs.skip_deploy != 'true' &&
        (inputs.deploy_trigger_paths == '' || steps.check-deploy.outputs.should_deploy == 'true')
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/${{ inputs.service_account_path }}
      run: |
        # Use environment variable if set (auto-detected), otherwise use input
        if [ -n "$APK_OUTPUT_PATH" ]; then
          APK_PATH="$APK_OUTPUT_PATH"
        else
          APK_PATH="${{ inputs.apk_output_path }}"
        fi
        RELEASE_NOTES_FILE="${{ inputs.release_notes_file }}"
        RELEASE_NOTES="${{ inputs.release_notes }}"
        GROUPS="${{ inputs.groups }}"
        TESTERS="${{ inputs.testers }}"

        echo "🔍 Using service account authentication"
        echo "📋 Service account file: $GOOGLE_APPLICATION_CREDENTIALS"
        echo "🔍 Using Firebase Android App ID: $FIREBASE_APP_ID_ANDROID"

        # Check if APK exists
        if [ ! -f "$APK_PATH" ]; then
          echo "❌ APK file not found: $APK_PATH"
          exit 1
        fi

        echo "📦 APK file: $APK_PATH ($(du -h "$APK_PATH" | cut -f1))"

        # Build deploy command
        DEPLOY_CMD="firebase appdistribution:distribute \"$APK_PATH\" --app \"$FIREBASE_APP_ID_ANDROID\""

        # Add release notes
        if [ -n "$RELEASE_NOTES_FILE" ] && [ -f "$RELEASE_NOTES_FILE" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --release-notes-file \"$RELEASE_NOTES_FILE\""
          echo "📝 Using release notes from: $RELEASE_NOTES_FILE"
        elif [ -n "$RELEASE_NOTES" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --release-notes \"$RELEASE_NOTES\""
          echo "📝 Using provided release notes text"
        fi

        # Add groups
        if [ -n "$GROUPS" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --groups \"$GROUPS\""
          echo "👥 Distributing to groups: $GROUPS"
        fi

        # Add testers
        if [ -n "$TESTERS" ]; then
          DEPLOY_CMD="$DEPLOY_CMD --testers \"$TESTERS\""
          echo "👥 Distributing to testers: $TESTERS"
        fi

        echo "🚀 Deploying to Firebase App Distribution..."
        echo "📋 Command: $DEPLOY_CMD"
        $DEPLOY_CMD

        echo "✅ Deployment completed"
