name: anyhoo_form_builder_widgets
resolution: workspace
description: "Flutter Form Builder adapters for Anyhoo design-system form widgets."
version: 0.2.1
homepage: https://anyhoosolutions.web.app/documentation/flutter_platform_kit
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.4 " # Or the corresponding Flutter version

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  anyhoo_design_system:
    path: ../anyhoo_design_system
  form_builder_validators: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
