name: Check Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-latest

    # Skip if PR title contains "WIP: "
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check version
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/check-version@main
