name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for version comparison

      - name: Prepare deployment
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/prepare-deployment@main
        with:
          app_name: "My App"
          verify_files: "lib/firebase_options.dart,firebase_service_account.json"
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      # Your deployment steps here...
      # - Version is available in CURRENT_VERSION env var
      # - Environment variables from .env are loaded
      # - Release notes are in deploy/release_notes.txt
      # - release_info.dart has been updated with build info
