name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for version comparison

      - name: Prepare deployment
        uses: Anyhoosolutions/flutter_platform_kit/tools/githubActions/prepare-deployment@main
        with:
          app_name: "My App"
          verify_files: "lib/firebase_options.dart,firebase_service_account.json"
          # Analysis options
          update_analysis_options: "true"
          analysis_options_ci_file: "analysis_options.yaml-ci"
          # Firebase setup
          setup_firebase: "true"
          firebase_project_id: "my-project-id"
          firebase_service_account_path: "firebase_service_account.json"
          # Functions build
          build_functions: "true"
          functions_path: "functions"
          functions_chmod_biome: "true"
          # Flutter setup
          setup_flutter: "true"
          flutter_version: "3.38.4"
          flutter_channel: "stable"
          flutter_analyze: "true"
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}

      # Your deployment steps here...
      # - Version is available in CURRENT_VERSION env var
      # - Environment variables from .env are loaded
      # - Release notes are in deploy/release_notes.txt
      # - release_info.dart has been updated with build info
      # - Firebase CLI is installed and authenticated
      # - Functions are built and ready
      # - Flutter is set up and dependencies are cached
      # - Flutter analyze has been run
