name: "Upload Documentation"
description: "Upload documentation to the documentation service"

inputs:
  upload_url:
    description: "The URL endpoint for uploading documentation"
    required: true
  dart_sdk:
    description: "Dart SDK version to use"
    required: false
    default: "3.5"
  project_root:
    description: "Root directory of the project (defaults to workspace)"
    required: false
    default: ${{ github.workspace }}
  commit_hash:
    description: "Optional commit hash for branch-based deployments"
    required: false
    default: ""
  pr_docs_base_url:
    description: "Base URL for PR documentation links (e.g., https://example.com/documentation)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ inputs.dart_sdk }}

    - name: Cache Dart packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}

    - name: Checkout upload tool
      shell: bash
      run: |
        echo ".."
        echo ".."
        echo ".."
        echo "===================================================="
        echo "====            CHECKOUT UPLOAD TOOL          ======"
        echo "===================================================="
        echo ".."
        echo ".."
        echo "Checking out upload tool from repository..."
        UPLOAD_TOOL_PATH="tools/upload_documentation"
        TOOL_DIR=$(dirname "$UPLOAD_TOOL_PATH")
        mkdir -p "$TOOL_DIR"
        git clone --depth 1 --branch main https://github.com/Anyhoosolutions/flutter_platform_kit.git /tmp/flutter_platform_kit
        if [ -d "/tmp/flutter_platform_kit/$UPLOAD_TOOL_PATH" ]; then
          cp -r /tmp/flutter_platform_kit/$UPLOAD_TOOL_PATH "$UPLOAD_TOOL_PATH"
          echo "✅ Upload tool checked out to $UPLOAD_TOOL_PATH"
        else
          echo "❌ Error: Upload tool path '$UPLOAD_TOOL_PATH' not found in repository"
          exit 1
        fi
        rm -rf /tmp/flutter_platform_kit

    - name: Run documentation upload
      shell: bash
      env:
        UPLOAD_URL: ${{ inputs.upload_url }}
      run: |
        echo ".."
        echo ".."
        echo ".."
        echo "===================================================="
        echo "====           RUN DOCUMENTATION UPLOAD       ======"
        echo "===================================================="
        echo ".."
        echo ".."
        UPLOAD_TOOL_PATH="tools/upload_documentation"
        if [ ! -d "$UPLOAD_TOOL_PATH" ]; then
          echo "❌ Error: Upload tool directory not found at $UPLOAD_TOOL_PATH"
          exit 1
        fi
        cd "$UPLOAD_TOOL_PATH" || exit 1
        if [ ! -f "bin/upload_documentation.dart" ]; then
          echo "❌ Error: upload_documentation.dart not found in $UPLOAD_TOOL_PATH/bin/"
          exit 1
        fi
        dart pub get --no-precompile
        echo "UPLOAD_URL: $UPLOAD_URL"
        if [ -n "${{ inputs.commit_hash }}" ]; then
          export GIT_COMMIT_HASH=${{ inputs.commit_hash }}
          dart bin/upload_documentation.dart --projectRoot=${{ inputs.project_root }} --commitHash=${{ inputs.commit_hash }}
        else
          dart bin/upload_documentation.dart --projectRoot=${{ inputs.project_root }}
        fi

    - name: Comment PR
      if: github.event_name == 'pull_request' && inputs.commit_hash != '' && inputs.pr_docs_base_url != ''
      uses: thollander/actions-comment-pull-request@v3
      with:
        message: |
          ${{ inputs.pr_docs_base_url }}/${{ inputs.commit_hash }}
