#!/usr/bin/env bash
# =============================================================================
# Generate minimal firebase_options.dart for emulator-based testing
# =============================================================================
# Avoids SOPS/decryption - creates placeholder values valid for Firebase emulators.
# Usage: generate-firebase-options.sh [PROJECT_ID] [OUTPUT_PATH]
#   PROJECT_ID: Firebase project ID (default: demo-project-id)
#   OUTPUT_PATH: Path relative to repo root (default: lib/firebase_options.dart)
# =============================================================================

set -e

PROJECT_ID="${1:-demo-project-id}"
OUTPUT_PATH="${2:-lib/firebase_options.dart}"

# Ensure project ID starts with "demo-" for Firebase demo project convention
if [[ ! "$PROJECT_ID" =~ ^demo- ]]; then
  PROJECT_ID="demo-${PROJECT_ID}"
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" << 'DART_EOF'
// Generated for emulator testing - no SOPS/decryption required
// File generated by tools/github_actions/manual_tests/scripts/generate-firebase-options.sh

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '12345',
    appId: '1:1:web:1',
    messagingSenderId: '',
    projectId: 'PROJECT_ID_PLACEHOLDER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '12345',
    appId: '1:1:android:1',
    messagingSenderId: '',
    projectId: 'PROJECT_ID_PLACEHOLDER',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '12345',
    appId: '1:1:ios:1',
    messagingSenderId: '',
    projectId: 'PROJECT_ID_PLACEHOLDER',
  );
}
DART_EOF

# Replace placeholder with actual project ID
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/PROJECT_ID_PLACEHOLDER/$PROJECT_ID/g" "$OUTPUT_PATH"
else
  sed -i "s/PROJECT_ID_PLACEHOLDER/$PROJECT_ID/g" "$OUTPUT_PATH"
fi

echo "Generated $OUTPUT_PATH with projectId: $PROJECT_ID"
