include: package:lints/recommended.yaml

analyzer:
  exclude: [
    lib/**.freezed.dart, 
    lib/**.g.dart, 
    ]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions